routes/funcio_routes.py
from flask import *
from classes.funcionario import User
import bcrypt
blue_funcio = Blueprint("func",__name__,template_folder = "templates")

@blue_funcio.route("/login", methods = ["GET","POST"])
def login_funcio(dados = ""):
    if request.method == "GET":
        return render_template("login_funcio.html")
    else:
        nome = request.form["nome"]
        senha = request.form["senha"]
        u1 = User()
        if(u1.check_pass(nome,senha)):
            session["User"] = nome
            if dados == "":
                dados = "/"
            return redirect(dados)
        else:
            return redirect("/funcionarios/login")

@blue_funcio.route("/add_funcio", methods = ["GET","POST"])
def add_funcio():
    u1 = User()
    if "User" in session:
        if request.method == "GET":
            return render_template("add_funcio.html")
        else:
            nome = request.form["nome"]
            senha = bcrypt.hashpw(request.form["senha"].encode("utf-8"),bcrypt.gensalt())
            u1.add_new(nome,senha)
            return redirect("/funcionarios/viewall_funcio")
    else:
        return redirect("/funcionarios/login")

@blue_funcio.route("/update_funcio/<_id_>", methods = ["GET","POST"])
def update_funcio(_id_):
    u1 = User()
    if "User" in session:
        if request.method == "GET":
            return render_template("update_funcio.html", dados = u1.view_one(_id_))
        else:
            nome = request.form["nome"]
            antiga_senha = request.form["antiga_senha"]
            nova_senha = request.form["senha"]
            confirma_nova_senha = request.form["senha2"]
            if nova_senha == confirma_nova_senha:
                u1 = User()
                if(u1.check_pass(_id_,antiga_senha)):
                    salt = bcrypt.gensalt()
                    senha = bcrypt.hashpw(nova_senha.encode("utf-8"),salt)
                    u1.update(nome,_id_,senha)
                    return redirect("/funcionarios/viewone_funcio/" + _id_ + "")
    else:
        return redirect("/funcionarios/login")


@blue_funcio.route("/delete_funcio/<_id_>", methods = ["GET", "POST"])
def delete_funcio(_id_):
    u1 = User()
    if "User" in session:
        if request.method == "GET":
            return render_template("delete_funcio.html", dados = u1.view_one(_id_))
        else:
            u1.delete(_id_)
            return redirect("/funcionarios/viewall_funcio")
    else:
        return redirect("funcionarios/login")

@blue_funcio.route("/viewall_funcio", methods = ["GET","POST"])
def viewall_funcio():
    u1 = User()
    if "User" in session:
        return render_template("viewall_funcio.html", dados = u1.view_all())
    else:
        return redirect("/funcionarios/login")

@blue_funcio.route("/viewone_funcio/<_id_>", methods = ["GET"])
def viewone_funcio(_id_):
    u1 = User()
    if "User" in session:
        return render_template("viewone_funcio.html", dados = u1.view_one(_id_))
    else:
        return redirect("/funcionarios/login")

routes/pedidos_routes.py
from flask import *
from classes.pedidos import Pedidos
from classes.itens import Itens
from classes.clientes import Clientes
from classes.itens_pedidos import Itens_Pedidos
<<<<<<< HEAD
import json
=======
import datetime
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
blue_pedidos = Blueprint("pedidos",__name__,template_folder = "templates")


@blue_pedidos.route("/add_pedido",methods = ["GET","POST"])
def add_pedido():
#    if "User" in session:
    if request.method == "GET":
        i1 = Itens()
        c1 = Clientes()
        return render_template("add_pedido.html",dados_clientes = c1.view_all(),dados = i1.view_all())
    else:
<<<<<<< HEAD
        print("POST")
        itens = request.get_json()
        print(itens)
        customer = itens["customer"]
        itens = itens["items"]
        p1 = Pedidos()
        p1.add_new(customer)
        id_pedido = p1.get_id(customer)
        for item in itens:
            print(item)
=======
        data = datetime.datetime.today().strftime("%Y-%m-%d")
        itens = request.get_json()
        status = True
        customer = itens["customer"]
        c1 = Clientes()
        customer_nome = c1.get_nome(customer)
        itens = itens["items"]
        p1 = Pedidos()
        p1.add_new(data,customer,status)
        id_pedido = p1.get_id(data,customer,status)
        for item in itens:
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
            id_produto = item["id"]
            nome = item["name"]
            price = item["price"]
            quantity = item["quantity"]
            ip1 = Itens_Pedidos()
<<<<<<< HEAD
            ip1.add_new(price,quantity,nome,id_produto,id_pedido)
            print("ok5")
            session["Carrinho"] = itens       
=======
            ip1.add_new(nome,quantity,price,id_produto,id_pedido)
            print("ok5")
            session["Carrinho"] = itens       
            #p1 = Pedidos()
            #p1.add_new(customer,status,itens)
            #print(id,nome,customer)
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
        msg = {"msg":"OK"}
        #MSG -> LINK PEDIDO OU CONTINUAR COMPRANDO
        return json.dumps(msg) 
            #redirect("/pedidos/viewall_pedidos")
    #else:
    #    return redirect("/funcionarios/login")

@blue_pedidos.route("/update_pedido/<_id_>", methods = ["GET","POST"])
def update_pedido(_id_):
    if "User" in session:
        if request.method == "GET":
            p1 = Pedidos()
            return render_template("update_pedido.html", dados = p1.view_one(_id_))

        else:
            nome = request.form["name"]
            status = True
            itens = request.form["itens"]
            p1 = Pedidos()
            p1.update(nome,status,itens,_id_)
            return redirect("/pedidos/viewone_pedido/" + _id_ + "")
    else:
        return redirect("/funcionarios/login")


@blue_pedidos.route("/delete_pedido/<_id_>", methods = ["GET", "POST"])
def delete_pedido(_id_):
    if "User" in session:
        if request.method == "GET":
            p1 = Pedidos()
            return render_template("delete_pedido.html", dados = p1.view_one(_id_))
        else:
            p1 = Pedidos()
            p1.delete(_id_)
            return redirect("/pedidos/viewall_pedido")
    else:
        return redirect("/funcionarios/login")

@blue_pedidos.route("/viewall_pedido", methods = ["GET","POST"])
def viewall_pedido():
    if "User" in session:
        p1 = Pedidos()
        return render_template("viewall_pedido.html", dados = p1.view_all())
    else:
        return redirect("/funcionarios/login")

@blue_pedidos.route("/viewone_pedido/<_id_>", methods = ["GET"])
def viewone_pedido(_id_):
    if "User" in session:
        p1 = Pedidos()
        return render_template("viewone_pedidos.html", dados = p1.view_one(_id_))
    else:
        return redirect("/funcionarios/login")

@blue_pedidos.route("/carrinho",methods = ["GET","POST"])
def carrinho():
    if "User" in session:
        if request.method == "GET":
            dados = "Carrinho" in session
            return render_template("carrinho.html",dados = dados)
        else:
            p1 = Pedidos()

    else:
        return redirect("/funcionarios/login")

@blue_pedidos.route("/picking/<_id_>", methods = ["GET"])
def picking(_id_):
    if "User" in session:
        if request.method == "GET":
            p1 = Pedidos()
            return render_template("picking.html", dados = p1.view_all_pedido(_id_))
        else:
            p1 = Pedidos()
            p1.turn_status(_id_)
        
    else:
        return redirect("/funcionarios/login")

templates/add_pedido.html
{%extends "layout.html"%}

{%block css%}
{%endblock%}

{%block content%}
<div class = "home">
    <h1 class = "logo"> Lista de itens </h1>
    <div class = "menu_crud">
      <strong><nav>
            <div class = "control-group col-md-8">
              <table class="table table-striped table-bordered" id="tabelaClientes" >
                <thead>
                  <tr>
                    <td> ID </td>
                    <td> Nome </td>
                    <td> CNPJ </td>
                    <td> Comprador </td>
                  </tr>
                </thead>
                <tbody>
                  {%for row in dados_clientes%}
                    <tr>
                      {%for col in row%}
                        <td>{{ col }}</td>
                      {%endfor%}
                      <td><input type = "Radio" value = "{{ row[0] }}" name = "customer" class = "customer"> Select this </td>
                    </tr>
                  {%endfor%}
                </tbody>
              </table>
              <table  class="table table-striped table-bordered" name="tabela" id="tabela" >
                <thead>
                  <tr>
                    <td data-name = "product_id"> ID </td>
                    <td data-name = "product_name"> Nome </td>
                    <td data-name = "product_esqt"> Em Estoque </td>
                    <td data-name = "product_price"> Preço </td>
<<<<<<< HEAD
                    <td> Endereço </td>
=======
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
                    <td> Opções </td>
                  </tr>
                </thead>
                <tbody>
                {%for row in dados%}
                  <tr class = "sc-product-item">
                  {%for col in row%}
                    <td>{{ col }}</td>
                  {%endfor%}
                    <div class = "buttons">
<<<<<<< HEAD
=======
                      <td><a class="btn btn-info" role = "button" href = "update_item/{{row[0]}}"> Alterar </a></td>
                      <td><a class="btn btn-info" role = "button" href = "viewone_item/{{row[0]}}"> Ver </a></td>
                      <td><a class="btn btn-info" role = "button" href = "delete_item/{{row[0]}}"> Deletar </a></td>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
                      <td><button class="btn btn-success my-cart-btn" data-id = "{{row[0]}}" data-name = "{{row[1]}}" data-quantity = 1 data-price = {{row[3]}} data-image = "{{ url_for('static',filename = 'img/dori.jpeg') }}">Add to cart</button></td>
                    </div>
                  </tr>
                {%endfor%}
                </tbody>
              </table>
          </div>
            <div class = "col-md-4 control-group">
                <div style="float: right; cursor: pointer;">
                    <span class="glyphicon glyphicon-shopping-cart my-cart-icon"><span class="badge badge-notify my-cart-badge"></span></span>
                </div>
                </form>
            </div>
    </div>
</div>
{%endblock%}
{%block js%}

<script src="{{url_for('static',filename = 'js/jquery.mycart.min.js')}}"></script>
<script src= "{{ url_for ('static',filename = 'js/datatables.min.js')}}"></script>
<script type="text/javascript">

  $(document).ready(function() {
    //DataTable
    $('#tabelaClientes').DataTable();
    //$('#tabela').DataTable();

    //cart
    var goToCartIcon = function($addTocartBtn){
    }
    var options = {
      currencySymbol: '$',
      classCartIcon: 'my-cart-icon',
      classCartBadge: 'my-cart-badge',
      classProductQuantity: 'my-product-quantity',
      classProductRemove: 'my-product-remove',
      classCheckoutCart: 'my-cart-checkout',
      affixCartIcon: true,
      showCheckoutModal: true,
      numberOfDecimals: 2,
      cartItems: [],
      clickOnAddToCart: function($addTocart){
        console.log($addTocart)
        goToCartIcon($addTocart);
      },
      afterAddOnCart: function(products, totalPrice, totalQuantity) {
        console.log("afterAddOnCart", products, totalPrice, totalQuantity);
      },
      clickOnCartIcon: function($cartIcon, products, totalPrice, totalQuantity) {
        console.log("cart icon clicked", $cartIcon, products, totalPrice, totalQuantity);
      },
      checkoutCart: function(products, totalPrice, totalQuantity) {
<<<<<<< HEAD
      var checkoutString;
      var checkoutJson;
      var my_items = '';
      var counter = 0;
=======
    var checkoutString;
  var my_items = '';
  var counter = 0;
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
    $.each(products, function(){
      my_items += '{"id":"'+this.id+'","name":"'+this.name+'","price":"'+this.price+'","quantity":"'+this.quantity+'"}';
      //my_items += 'id='+this.id+'&name='+this.name+'&price='+this.price+'&quantity='+this.quantity+'';
      counter++;        
      if (counter<totalQuantity){
        my_items +=",";
      }
          });
<<<<<<< HEAD
      cst = $('.customer:checked').val();
      //checkoutString = '{"customer":"'+cst+'","items": ['+my_items+']}'; //JSON.stringify(     JSON.parse(
      checkoutString = {"customer":""+cst+"","items": [''+my_items+'']};
      checkoutJson = JSON.stringify(checkoutString);
      //checkoutString = '{"items": ['+my_items+']}';
    $.ajax({
        contentType: 'application/json',
        type: "POST",
        url: "{{ url_for('pedidos.add_pedido') }}",
        //data: checkoutString,
        data: checkoutJson,
        success: function( data ) {
          console.log("---> "+data.msg)
          $( '#customer_name' ).html( 'Resultados: ' + data.length );
        }
    });
       console.log("checking out", products, totalPrice, totalQuantity, checkoutString);
       },
=======
    cst = $('.customer:checked').val();
    //cst = $('#customer_id').text();
  checkoutString = '{"customer":"'+cst+'","items": ['+my_items+']}'; //JSON.stringify(     JSON.parse(
  //checkoutString = '{"items": ['+my_items+']}';
    $.ajax({
      contentType: 'application/json',
        type: "POST",
        url: "{{ url_for('pedidos.add_pedido') }}",
      data: checkoutString,
      success: function( data ) {
        console.log("---> "+data.msg)
        $( '#customer_name' ).html( 'Resultados: ' + data.length );
      }
    });
       console.log("checking out", products, totalPrice, totalQuantity, checkoutString);
      },
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
    };

      // Initialize the leaveStep event
      $(".my-cart-btn").myCart(options);
  }); 
</script>
{%endblock%}

templates/carrinho.html
{%extends "layout.html"%}
{%block content%}
<div class = "home">
    <h1 class = "logo"> Itens do pedido </h1>
    <div class = "menu_crud">
      <strong><nav>
        <form class = "form-vertical" method = "post">
          	<div class = "control-group">
            	<table class="table table-striped table-bordered" name="tabela" id="tabela" >
					<thead>
						<tr>
							<td> ID </td>
							<td> Nome </td>
							<td> Preço </td>
							<td> Quantidade </td>
							<td> Opções </td>
						</tr>
					</thead>
					<tbody>
					{%for row in dados%}
						<tr>
						{%for col in row%}
							<td>{{ col }}</td>
						{%endfor%}
							<div class = "buttons">
								<td><a class = "btn btn-info" role = "button" href = "update_funcio/{{row[0]}}"> Alterar </a></td>
								<td><a class = "btn btn-info" role = "button" href = "viewone_funcio/{{row[0]}}"> Ver </a></td>
								<td><a class = "btn btn-info" role = "button" href = "delete_funcio/{{row[0]}}"> Deletar </td>
							</div>
						</tr>
					{%endfor%}
					</tbody>
				</table>
    		</div>
        </form>
    </div>
</div>
{%endblock%}

templates/delete_funcio.html
{%extends "layout.html"%}
{%block content%}
<div class = "home">
    <h1 class = "logo"> Deletar registro </h1>
    <div class = "menu_crud">
      <strong><nav>
        <form class = "form-vertical" action = "{{ dados[0] }}" method = "post">
          <div class = "control-group">
            <label class = "control-label"> Registro </label>
            <div class = "controls">
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>NOME</th>  
                  </tr>           
                </thead>
                <tbody>
                  <tr>
                    <td>{{ dados[0] }}</td>
                    <td>{{ dados[1] }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
              <div class = "form-actions">
                <p class = "Danger"> Tem Certeza que deseja apagar permanentemente este registro? </p>
                <button type = "submit" class = "btn btn-danger"> Sim </button>
              </div>
          </div>
        </form>
    </div>
  </div>
{%endblock%}

templates/delete_pedidos.html
{%extends "layout.html"%}
{%block content%}
<div class = "home">
    <h1 class = "logo"> Deletar registro </h1>
    <div class = "menu_crud">
      <strong><nav>
        <form class = "form-vertical" action = "{{ dados[0] }}" method = "post">
          <div class = "control-group">
            <label class = "control-label"> Registro </label>
            <div class = "controls">
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Cliente</th>
                    <th>Status</th>
                    <th>Produtos</th> 
                  </tr>           
                </thead>
                <tbody>
                  <tr>
                    <td>{{ dados[0] }}</td>
                    <td>{{ dados[1] }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
              <div class = "form-actions">
                <p class = "Danger"> Tem Certeza que deseja apagar permanentemente este registro? </p>
                <button type = "submit" class = "btn btn-danger"> Sim </button>
              </div>
          </div>
        </form>
    </div>
  </div>
{%endblock%}

templates/funcionarios.html
{%extends "layout.html"%}
{%block content%}
	<div class = "home">
		<h1 class = "logo"> Funcionarios </h1>
		<div class = "menu_crud">
			<strong><nav>
				<ul class = "menu_crud">
<<<<<<< HEAD
					<li><a class = "btn btn-default" href = "{{url_for('func.add_funcio')}}">Adicionar novo </a></li>
					<li><a class = "btn btn-default" href = "{{url_for('func.viewall_funcio')}}">Ver lista </a></li>
=======
					<li><a class = "btn btn-info" role = "button" href = "{{url_for('func.add_funcio')}}">Adicionar novo </a></li>
					<li><a class = "btn btn-info" role = "button" href = "{{url_for('func.viewall_funcio')}}">Ver lista </a></li>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
				</ul>
		</div>
	</div>
{%endblock%}

templates/layout.html
<!doctype html>
  <html>
    <head>
      <title> WMS Simplify It </title>
      <link rel = "stylesheet" href="{{url_for('static',filename = 'css/bootstrap.min.css')}}" />
      <link rel = "stylesheet" href="{{url_for('static',filename = 'css/style.css')}}">
      <link rel = "stylesheet" href="{{url_for('static',filename = 'css/datatables.min.css')}}">
      {%block css%}
      {%endblock%}
    </head>
    <body>
      <header>
        <div class = "container">
          <h1 class = "logo"> Simplify It </h1>
          <strong><nav>
            <ul class = "menu">
              <li><a href = "{{ url_for('site.home') }}"> Home </a></li>
              <li><a href = "{{ url_for('site.about') }}"> About </a></li>
	     			  <li><a href = "{{ url_for('site.itens') }}"> Produtos </a></li>
	            <li><a href = "{{ url_for('site.funcionarios') }}"> Funcionarios </a></li>
	            <li><a href = "{{ url_for('site.pedidos') }}"> Pedidos </a></li>
              <li><a href = "{{ url_for('site.clientes') }}"> Clientes </a></li>
              <li><a href = "{{ url_for('pedidos.carrinho') }}"> Carrinho </a></li>
            </ul>
          </nav></strong>
        </div>
      </header>
      <div class = "container">
        {%block content%}
        {%endblock%}
      </div>
      <script src="{{ url_for('static',filename = 'js/jquery-2.2.3.min.js')}}"></script>
      
        {%block js%}
        {%endblock%}      
        <script src="{{ url_for('static',filename = 'js/bootstrap.min.js')}}"></script>
    </body>
  </html>

templates/login.html
{%extends "layout.html"%}
{%block content%}
{% if session['logged_in'] %}
    <p>You're logged in already!</p>
{% else %}
  <form action="/login" method="POST">
  <div class="login">
  	<div class="login-screen">
  		<div class="app-title">
  			<h1>Login</h1>
  		</div>

  		<div class="login-form">
  			<div class="control-group">
  			     <input type="text" class="login-field" value="" placeholder="username" name="nome">
  			     <label class="login-field-icon fui-user" for="login-name"></label>
  			</div>

  			<div class="control-group">
  			     <input type="password" class="login-field" value="" placeholder="password" name="senha">
  			     <label class="login-field-icon fui-lock" for="login-pass"></label>
  			</div>
              <input type="submit" value="Log in" class="btn btn-primary btn-large btn-block" >
  		    <br>
  		</div>
  	</div>
  </div>
  </form>
{%endif%}
{%endblock%}

templates/pedidos.html
{%extends "layout.html"%}
{%block content%}
	<div class = "home">
		<h1 class = "logo"> Pedidos </h1>
		<div class = "menu_crud">
			<strong><nav>
				<ul class = "menu_crud">
<<<<<<< HEAD
					<li><a class = "btn btn-default" href = "{{url_for('pedidos.add_pedido')}}">Adicionar novo </a></li>
					<li><a class = "btn btn-default" href = "{{url_for('pedidos.viewall_pedido')}}">Ver lista </a></li>
=======
					<li><a class = "btn btn-info" role = "button" href = "{{url_for('pedidos.add_pedido')}}">Adicionar novo </a></li>
					<li><a class = "btn btn-info" role = "button" href = "{{url_for('pedidos.viewall_pedido')}}">Ver lista </a></li>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
				</ul>
		</div>
	</div>
{%endblock%}

templates/update_clientes.html
{%extends "layout.html"%}
{%block content%}
	<div class = "home">
		<h1 class = "logo"> Atualizar informações </h1>
		<div class = "menu_crud">
			<strong><nav>
				<form class = "form-vertical" action = "clientes.clientes_update" method = "post">
					<div class = "control-group">
						<label class = "control-label"> Nome </label>
						<label class = "control-label"> CNPJ </label>
						<div class = "controls">
							<input name = "nome" type = "text" placeholder = "Novo nome!" value = "{{ dados[1] }}">
							<input name = "cnpj" type = "text" placeholder = "Novo CNPJ!" value = "{{ dados[2] }}">
						</div>
						<div class = "form-actions">
							<button type = "submit" class = "btn btn-sucess"> Salvar </button>
<<<<<<< HEAD
								<a class = "btn btn-default" href = "{{url_for('site.clientes')}}"> Voltar </a>
=======
								<a class = "btn btn-info" role = "button" href = "{{url_for('site.clientes')}}"> Voltar </a>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
						</div>
					</div>
				</form>
		</div>
	</div>
{%endblock%}

templates/update_item.html
{%extends "layout.html"%}
{%block content%}
	<div class = "home">
		<h1 class = "logo"> Atualizar informações </h1>
		<div class = "menu_crud">
			<strong><nav>
				<form class = "form-vertical" action "func.func_update" method = "post">
					<div class = "control-group">
						<label class = "control-label"> Nome </label>
            <label class = "control-label"> Quantidade </label>
            <label class = "control-label"> Preço </label>
						<div class = "controls">
							<input name = "name" type = "text" placeholder = "Novo nome!" value = "{{ dados[1] }}">
          					<input name = "quantity" type = "text" placeholder = "Nova quantidade!" value = "{{ dados[2] }}">
              				<input name = "price" type = "text" placeholder = "Novo preço!" value = "{{ dados[3] }}">
						</div>
						<div class = "form-actions">
							<button type = "submit" class = "btn btn-sucess"> Salvar </button>
<<<<<<< HEAD
							<a type = "submit" class = "btn" href = "{{url_for('site.itens')}}"> Voltar </a>
=======
							<a type = "submit" role = "button" class = "btn btn-info" href = "{{url_for('site.itens')}}"> Voltar </a>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
						</div>
					</div>
				</form>
		</div>
	</div>
{%endblock%}

templates/update_pedidos.html
{%extends "layout.html"%}
{%block content%}
	<div class = "home">
		<h1 class = "logo"> Atualizar informações </h1>
		<div class = "menu_crud">
			<strong><nav>
				<form class = "form-vertical" method = "post">
					<div class = "control-group">
						<label class = "control-label"> Cliente </label>
						<label class = "control-label"> Status </label>
						<label class = "control-label"> Pedidos </label>
						<div class = "controls">
							<input name = "nome" type = "text" placeholder = "Novo cliente!" value = "{{ dados[1] }}">
						</div>
						<div class = "form-actions">
							<button type = "submit" class = "btn btn-sucess"> Salvar </button>
<<<<<<< HEAD
								<a class = "bt btn-default" href = "{{url_for('site.pedidos')}}"> Voltar </a>
=======
								<a class = "btn btn-info" role = "button" href = "{{url_for('site.pedidos')}}"> Voltar </a>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
						</div>
					</div>
				</form>
		</div>
	</div>
{%endblock%}

templates/viewall_funcio.html
{%extends "layout.html"%}
{%block content%}
<div class = "home">
    <h1 class = "logo"> Lista de funcionários </h1>
    <div class = "menu_crud">
      <strong><nav>
        <form class = "form-vertical" action = "add_funcio" method = "post">
          	<div class = "control-group col-md-8">
            	<table class="table table-striped table-bordered" name="tabela" id="tabela" >
					<thead>
						<tr>
							<td> ID </td>
							<td> Nome </td>
							<td> Opções </td>
						</tr>
					</thead>
					<tbody>
					{%for row in dados%}
						<tr>
						{%for col in row%}
							<td>{{ col }}</td>
						{%endfor%}
							<div class = "buttons">
<<<<<<< HEAD
								<td><a class = "btn btn-default" href = "update_funcio/{{row[0]}}"> Alterar </a></td>
								<td><a class = "btn btn-default" href = "viewone_funcio/{{row[0]}}"> Ver </a></td>
								<td><a class = "btn btn-default" href = "delete_funcio/{{row[0]}}"> Deletar </a></td>
=======
								<td><a class = "btn btn-info" role = "button"  href = "update_funcio/{{row[0]}}"> Alterar </a></td>
								<td><a class = "btn btn-info" role = "button"  href = "viewone_funcio/{{row[0]}}"> Ver </a></td>
								<td><a class = "btn btn-info" role = "button"  href = "delete_funcio/{{row[0]}}"> Deletar </a></td>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
							</div>
						</tr>
					{%endfor%}
					</tbody>
				</table>
    		</div>
        </form>
    </div>
</div>
{%endblock%}

templates/viewall_item.html
{%extends "layout.html"%}

{%block css%}
{%endblock%}

{%block content%}
  <div class = "home">
    <h1 class = "logo"> Lista de itens </h1>
    <div class = "menu_crud">
    <strong><nav>
      <div class = "control-group col-md-8">
        <table  class="table table-striped table-bordered" name="tabela" id="tabela" >
          <thead>
            <tr>
              <td data-name = "product_id"> ID </td>
              <td data-name = "product_name"> Nome </td>
              <td data-name = "product_esqt"> Em Estoque </td>
              <td data-name = "product_price"> Preço </td>
<<<<<<< HEAD
              <td> Endereço </td>
=======
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
              <td> Opções </td>
            </tr>
          </thead>
        <tbody>
          {%for row in dados%}
            <tr class = "sc-product-item">
              {%for col in row%}
                <td>{{ col }}</td>
              {%endfor%}
            <div class = "buttons">
<<<<<<< HEAD
              <td><a class="btn btn-default" href = "update_item/{{row[0]}}"> Alterar </a></td>
              <td><a class="btn btn-default" href = "viewone_item/{{row[0]}}"> Ver </a></td>
              <td><a class="btn btn-default" href = "delete_item/{{row[0]}}"> Deletar </a></td>
=======
              <td><a class = "btn btn-info" role = "button" href = "update_item/{{row[0]}}"> Alterar </a></td>
              <td><a class = "btn btn-info" role = "button" href = "viewone_item/{{row[0]}}"> Ver </a></td>
              <td><a class = "btn btn-info" role = "button" href = "delete_item/{{row[0]}}"> Deletar </a></td>
>>>>>>> 0e1cc2230c3d6d66ced139d7527679d1bceb3364
            </div>
            </tr>
          {%endfor%}
        </tbody>
        </table>
  </div>
{%endblock%}